services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: react_frontend
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data: