services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "80:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000,http://react_frontend:3000,*
    volumes:
      - ./backend:/app  # Map local backend directory to container

  frontend:
    build: ./frontend
    container_name: react_frontend
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - WDS_SOCKET_PORT=3000
      - WATCHPACK_POLLING=true  # Enable polling for file changes
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file watcher
      - FAST_REFRESH=true  # Enable fast refresh for React
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount local directory to container
      - /app/node_modules  # Use container's node_modules
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install &&
             npm run dev"

volumes:
  postgres_data: