"""add first and last name to users

Revision ID: c5a927c233e2
Revises: 665b7d3f489a
Create Date: 2025-06-14 13:00:02.106068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a927c233e2'
down_revision: Union[str, None] = '665b7d3f489a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.execute("UPDATE users SET first_name = 'Unknown' WHERE first_name IS NULL")
    op.alter_column('users', 'first_name', nullable=False)
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.execute("UPDATE users SET last_name = 'Unknown' WHERE last_name IS NULL")
    op.alter_column('users', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
