"""create upcoming presentations table

Revision ID: ff866cda9270
Revises: bd247016fb11
Create Date: 2025-06-30 21:53:18.523398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff866cda9270'
down_revision: Union[str, None] = 'bd247016fb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming_presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('presentation_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upcoming_presentations_id'), 'upcoming_presentations', ['id'], unique=False)
    op.create_index(op.f('ix_upcoming_presentations_user_id'), 'upcoming_presentations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upcoming_presentations_user_id'), table_name='upcoming_presentations')
    op.drop_index(op.f('ix_upcoming_presentations_id'), table_name='upcoming_presentations')
    op.drop_table('upcoming_presentations')
    # ### end Alembic commands ###
